name: blood_donation
description: Blood Donation Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.6.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.9
  internet_connection_checker: ^3.0.1
  shared_preferences: ^2.2.2
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  provider: ^6.1.1
  dio: ^5.4.0
  image_cropper: ^8.1.0
  image_picker: ^1.0.7
  infinite_scroll_pagination: ^4.0.0
  moment_dart: ^3.0.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.0
  flutter_map_cancellable_tile_provider: ^3.0.2
  url_launcher: ^6.3.1
  flutter_rating_bar: ^4.0.1
  firebase_core: ^3.9.0
  firebase_messaging: ^15.1.6
  animations: ^2.0.11
  uuid: ^4.5.1
  connectivity_plus: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
